tunnel: d722d85b-87fc-46aa-af20-c48eddc78c76
credentials-file: /Users/sergejkosilov/.cloudflared/d722d85b-87fc-46aa-af20-c48eddc78c76.json

ingress:
  - hostname: app.coffe-ug.ru
    service: http://localhost:4200
  - hostname: api.coffe-ug.ru
    service: http://localhost:3001
  - service: http_status:404
