version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: coffee_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coffee_admin
      MYSQL_USER: coffee_user
      MYSQL_PASSWORD: coffee_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffee_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # NestJS Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffee_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: coffee_user
      DB_PASSWORD: coffee_password
      DB_DATABASE: coffee_admin
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - coffee_network
    command: npm run start:dev

  # Angular/Ionic Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coffee_frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
      - "8100:8100"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - coffee_network
    command: npm start

volumes:
  mysql_data:

networks:
  coffee_network:
    driver: bridge
