version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: coffee_mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: coffee_admin
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_prod_data:/var/lib/mysql
    networks:
      - coffee_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    image: coffee-backend:latest
    container_name: coffee_backend_prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: coffee_admin
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coffee_network

  frontend:
    image: coffee-frontend:latest
    container_name: coffee_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - coffee_network

volumes:
  mysql_prod_data:

networks:
  coffee_network:
    driver: bridge
