version: '3.8'

services:
  # NestJS Backend for Yandex Cloud
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffee_backend_prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # Database settings for Yandex Cloud MySQL
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SSL: ${DB_SSL:-true}
      # JWT Secret (generate strong random string)
      JWT_SECRET: ${JWT_SECRET}
      # Email settings
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    volumes:
      # Mount uploads directory for file storage
      - uploads_data:/app/uploads
    networks:
      - coffee_prod_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/test/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads_data:

networks:
  coffee_prod_network:
    driver: bridge