#!/bin/bash

# ============================================
# Quick Production Deploy Commands
# Быстрые команды для деплоя на продакшен
# ============================================

echo "🚀 Coffee Admin - Production Migration Deploy"
echo "=============================================="
echo ""
echo "Используйте одну из команд ниже:"
echo ""
echo "1️⃣  АВТОМАТИЧЕСКИЙ ДЕПЛОЙ (рекомендуется):"
echo "   bash scripts/apply-production-seed.sh"
echo ""
echo "2️⃣  РУЧНОЙ ДЕПЛОЙ:"
echo "   # Шаг 1: Загрузить файл на сервер"
echo "   scp scripts/seed-production-orders.sql user1@192.144.12.102:~/coffe/"
echo ""
echo "   # Шаг 2: Подключиться к серверу"
echo "   ssh user1@192.144.12.102"
echo ""
echo "   # Шаг 3: Выполнить миграцию"
echo "   cd ~/coffe"
echo "   DB_PASSWORD=\$(grep MYSQL_ROOT_PASSWORD docker-compose.fallback.yml | awk '{print \$2}')"
echo "   docker exec -i coffee_mysql_fallback mysql -uroot -p\"\${DB_PASSWORD}\" coffee_db < seed-production-orders.sql"
echo ""
echo "3️⃣  ПРОВЕРИТЬ РЕЗУЛЬТАТ:"
echo "   # На сервере:"
echo "   docker exec -i coffee_mysql_fallback mysql -uroot -p\"\${DB_PASSWORD}\" coffee_db -e \\"
echo "     \"SELECT status, COUNT(*) as count FROM orders \\"
echo "     WHERE createdAt >= DATE_FORMAT(NOW(), '%Y-%m-01') \\"
echo "     GROUP BY status;\""
echo ""
echo "   # Или в браузере:"
echo "   https://coffe-ug.ru/orders"
echo ""
echo "4️⃣  ОТКАТ (если нужно):"
echo "   docker exec -i coffee_mysql_fallback mysql -uroot -p\"\${DB_PASSWORD}\" coffee_db -e \\"
echo "     \"DELETE FROM orders WHERE createdAt >= DATE_FORMAT(DATE_SUB(NOW(), INTERVAL 1 MONTH), '%Y-%m-01');\""
echo ""
echo "=============================================="
echo "📚 Полная документация: migration_guide.md"
echo "=============================================="
